version: '2'

services:

  bro:
    image: blacktop/bro
    command: -i eth0
    volumes:
      - ./bro:/pcap:rw
    cap_add:
      - NET_RAW
    networks:
      - elk

  elasticsearch:
    build: 
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - bro 

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./bro:/usr/share/logstash/bro:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  4ceeduploader:
    image: t2c2/4ceeduploader:16.10.2
    ports:
      - "8888:8000"
    environment:
      CURATOR_HOME: "http://192.17.237.43:32500"
      CURATOR_API_URL: "http://192.17.237.43:32500/api/"
      UPLOADER_HOME: "http://bracelet-test-1.cs.illinois.edu:8888/4ceeduploader/"
    networks:
      - elk

networks:

  elk:
    driver: bridge
