version: '2'

services:

  bro:
    image: blacktop/bro
    command: -i eth0
    volumes:
      - ./bro:/pcap:rw
    cap_add:
      - NET_RAW
    network_mode: "host"

  elasticsearch:
    build: 
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    expose:
      - "9200"
      - "9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - bro 

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./bro:/usr/share/logstash/bro:ro
    expose:
      - "5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  4ceeduploader:
    image: t2c2/4ceeduploader:18.06.09
    ports:
      - "8888:8000"
    environment:
      CURATOR_HOME: "http://bracelet-srv-test.engr.illinois.edu/curatorhome/"
      CURATOR_API_URL: "http://bracelet-srv-test.engr.illinois.edu/curatorapi/"
      UPLOADER_HOME: "http://bracelet-srv-test.engr.illinois.edu:8888"
    networks:
      - elk

networks:

  elk:
    driver: bridge
